app = "listmonk"

[build]
runtime = "docker"
image = "listmonk/listmonk:latest"

[http]
port = 9000
health_check_path = "/api/health"

[env]
LISTMONK_app__address = "0.0.0.0:9000"
LISTMONK_db__host = "postgres"
LISTMONK_db__port = "5432"
LISTMONK_db__user = "postgres"
LISTMONK_db__password = "${{secrets.PGPASSWORD}}"
LISTMONK_db__database = "listmonk"

[vm]
package = "g1.small"
instances = 1
