app = "focalboard"

[build]
runtime = "docker"
image = "mattermost/focalboard:latest"

[http]
port = 8000
health_check_path = "/api/v2/ping"

[env]
FOCALBOARD_DB_TYPE = "postgres"
FOCALBOARD_DB_CONFIG = "postgres://postgres:${{secrets.PGPASSWORD}}@postgres:5432/focalboard?sslmode=disable"

[vm]
package = "g1.small"
instances = 1
