app = "directus"

[build]
runtime = "docker"
image = "directus/directus:11"

[http]
port = 8055
health_check_path = "/server/health"

[env]
DB_CLIENT = "pg"
DB_HOST = "postgres"
DB_PORT = "5432"
DB_DATABASE = "directus"
DB_USER = "postgres"
DB_PASSWORD = "${{secrets.PGPASSWORD}}"
ADMIN_EMAIL = "admin@example.com"
ADMIN_PASSWORD = "${{secrets.ADMIN_PASSWORD}}"
KEY = "${{secrets.DIRECTUS_KEY}}"
SECRET = "${{secrets.DIRECTUS_SECRET}}"

[vm]
package = "g1.small"
instances = 1
