app = "postal"

[build]
runtime = "docker"
image = "ghcr.io/postalserver/postal:latest"

[http]
port = 25
health_check_path = "/"

[env]
POSTAL_FNAME = "Postal"
MYSQL_HOST = "mysql"
MYSQL_PORT = "3306"
MYSQL_DATABASE = "postal"
MYSQL_USER = "postal"
MYSQL_PASSWORD = "${{secrets.MYSQL_PASSWORD}}"

[vm]
package = "g1.small"
instances = 1
