app = "wekan"

[build]
runtime = "docker"
image = "ghcr.io/wekan/wekan:latest"

[http]
port = 8080
health_check_path = "/"

[env]
MONGO_URL = "mongodb://mongo:27017/wekan"
ROOT_URL = "http://localhost:8080"
WRITABLE_PATH = "/data"

[vm]
package = "g1.small"
instances = 1
