app = "wordpress"

[build]
runtime = "docker"
image = "wordpress:6-php8.3"

[http]
port = 80
health_check_path = "/"

[env]
WORDPRESS_DB_HOST = "mysql"
WORDPRESS_DB_USER = "wordpress"
WORDPRESS_DB_PASSWORD = "${{secrets.MYSQL_PASSWORD}}"
WORDPRESS_DB_NAME = "wordpress"

[vm]
package = "g1.small"
instances = 1
