app = "leantime"

[build]
runtime = "docker"
image = "leantime/leantime:latest"

[http]
port = 80
health_check_path = "/"

[env]
LEAN_DB_HOST = "mysql"
LEAN_DB_PORT = "3306"
LEAN_DB_DATABASE = "leantime"
LEAN_DB_USER = "leantime"
LEAN_DB_PASSWORD = "${{secrets.MYSQL_PASSWORD}}"

[vm]
package = "g1.small"
instances = 1
